name: twitter_clone_apps
description: Twitter Clone project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # riverpod
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

  # freezed
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # utils
  image_picker: ^1.0.0
  permission_handler: ^10.3.0
  collection: ^1.17.0
  timeago: ^3.4.0
  recase: ^4.1.0
  clock: ^1.1.1
  uuid: ^3.0.7
  intl: ^0.18.0
  equatable: ^2.0.5
  url_launcher: ^6.1.6
  fpdart: ^0.6.0

  # ui
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2
  smooth_page_indicator: ^1.0.1
  carousel_slider: ^4.2.1
  any_link_preview: ^3.0.0

  # fonts
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.5
  heroicons: ^0.8.0

  # appwrite
  appwrite: ^9.0.1

  # plus packages
  share_plus: ^7.0.2
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_launcher_icons: ^0.13.0

  # riverpod
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3

  # freezed
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter_launcher_icons:
  ios: true
  android: true
  image_path: assets/images/app_icon.jpg
  remove_alpha_ios: true

flutter_gen:
  output: lib/generated/
  line_length: 150

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
